"""Built-in profile names, for autocomplete. Generated by tools/make_builtin.py; do not edit.

    spark_tls.Session(spark_tls.ios26.native_apple)
    spark_tls.Session(spark_tls.chrome_151)
"""


class ios26:
    """iOS 26 profiles."""

    bing_34 = 'IOS-26-bing-34'
    """Microsoft Bing app 34 on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    brave = 'IOS-26-brave'
    """Brave on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    chrome_155 = 'IOS-26-chrome-155'
    """Chrome 155 on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    duckduckgo = 'IOS-26-duckduckgo'
    """DuckDuckGo browser on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    edge_153 = 'IOS-26-edge-153'
    """Edge 153 on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    firefox_157 = 'IOS-26-firefox-157'
    """Firefox 157 on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    native_apple = 'IOS-26-native-apple'
    """Native iOS 26 app (NSURLSession/CFNetwork), captured from Uber Eats; set your app's user-agent"""

    native_webkit_tls = 'IOS-26-native-webkit-tls'
    """Native iOS 26 app request with the WebKit/Safari TLS (20 ciphers) and native HTTP/2; captured from HelloFresh (Iterable SDK); set your app's user-agent"""

    opera_6 = 'IOS-26-opera-6'
    """Opera 6.7 on iOS 26 (WebKit: same TLS + HTTP/2 as every iOS browser app, own user-agent)"""

    safari = 'ios-safari-26'
    """Safari on iOS 26"""

    webview_apple = 'IOS-26-webview-apple'
    """In-app webview on iOS 26 (WKWebView): native TLS + HTTP/2, webview user-agent"""


chrome_151 = 'chrome-151'
"""Chrome 151 (Windows)"""

__all__ = ['ios26', 'chrome_151']
